{
 "title": "SRE   Overview dashboard",
 "description": "1. Calculate Error Rate (Availability SLI):\n  > \"Show me the percentage of failed requests for the /api/v1/orders endpoint over the last 5 minutes.\"\n\n   1 sum(rate(http_requests_total{status=\"500\", endpoint=\"/api/v1/orders\"}[5m]))\n   2 /",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(rate(http_requests_total{endpoint=\"/api/v1/orders\"}[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " sum(rate(http_requests_total{status=\"500\", endpoint=\"/api/v1/orders\"}[5m]))",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum(rate(http_requests_total{status=\"500\", endpoint=\"/api/v1/orders\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Site Uptime (1=UP, 0=DOWN)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "P95 Latency (Seconds)",
   "type": "timeseries",
   "description": "  This measures the performance of your Mock App.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, endpoint) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "__unconfigured-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  }
 ]
}